### ISSUE TITLE
i2p.plugins.tor-manager OSX

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2P-Secure-Design-Collective#31]
https://github.com/eyedeekay/i2p.plugins.tor-manager
https://github.com/eyedeekay/i2p.plugins.tor-manager/releases/tag/0.0.4

**Comment by Shoalsteed** [comment]
Testing on an old mac - High Sierra.
Fresh Install of I2P using the DMG.
Successfully installed file in plugins.
Testing with M1 as well. 
<img width="751" alt="Screen Shot 2022-02-15 at 2 48 48 PM" src="https://user-images.githubusercontent.com/50714166/154138472-e668c111-b0b9-406b-bf16-4becb632e455.png">

**Comment by Shoalsteed** [comment]
Started plugin.
I have I2PIPB installed, it has not been updated since August last year ( not using this machine anymore)
Checked for updates and it found none
Disabled it.

**Comment by Shoalsteed** [comment]
<img width="335" alt="Screen Shot 2022-02-15 at 2 56 28 PM" src="https://user-images.githubusercontent.com/50714166/154139031-2f6ac06b-017c-4efe-a037-25945232c6e3.png">

Suggestion: choose one name. or create a new one ? I2P 2Tor Browser ? ie

**Comment by Shoalsteed** [comment]
<img width="870" alt="Screen Shot 2022-02-15 at 2 49 48 PM" src="https://user-images.githubusercontent.com/50714166/154139284-64cce8a8-f75d-4353-8a4a-2a1cd6438c69.png">
clicking on the plugin lead to this.
Since I have disabled I2PIPB, is that the issue? Or can I use this on its own?
Do I need to wait to use it?
What sort of troubleshooting should I consider? 
How do I know when this is ready to use?

**I updated Firefox and reinstalled I2PIPB and restarted the router.**

**I still cannot access anything with the plugin**

<img width="985" alt="Screen Shot 2022-02-15 at 3 24 21 PM" src="https://user-images.githubusercontent.com/50714166/154143371-eebc1adb-477b-4e99-9800-16ec8660941d.png">
<img width="854" alt="Screen Shot 2022-02-15 at 3 24 26 PM" src="https://user-images.githubusercontent.com/50714166/154143372-716fa9ae-e67b-400b-9385-d14dbe166965.png">
<img width="286" alt="Screen Shot 2022-02-15 at 3 24 36 PM" src="https://user-images.githubusercontent.com/50714166/154143374-40577643-5e46-46a4-940e-f777722c7d75.png">
<img width="233" alt="Screen Shot 2022-02-15 at 3 24 41 PM" src="https://user-images.githubusercontent.com/50714166/154143375-05942f3f-4895-4c91-aa7e-9c7f506d3582.png">

**Comment by Shoalsteed** [comment]
Suggestion from download and install workflow:
- clicking on files can be intimidating. 
- assumes I know which to pick or that su3 is a plugin.
- not sure what to look for to understand if the plugin is not working except that it leads to a 404 page?
- create download / troubleshooting WiP so that we can take into account people who are not dev or I2P familiar. This is especially true for Tor users who may want to make use of this. Consider their expectations for usability based on Tor's UX.

**Comment by Shoalsteed** [comment]
Tried with amd64su file , but arm file was accepted and installed.

**Comment by Shoalsteed** [comment]
still unable to access anything other than a 404 page after a half hour. I have participating tunnels, and a share ratio for router health.

**Comment by Shoalsteed** [comment]
I was unsuccessful in testing the plugin since I am not sure what should happen if I click on it and only got a 404 page on two machines running the latest I2P with Firefox, I2PIPB running latest versions.

**Comment by Shoalsteed** [comment]
[darwin-arm64] uter.startup.LoadClientAppsJob: Error starting up the client class net.i2p.router.web.ShellService
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at net.i2p.router.startup.LoadClientAppsJob$RunApp.run(LoadClientAppsJob.java:308)
    at java.lang.Thread.run(Thread.java:748)
    at net.i2p.util.I2PThread.run(I2PThread.java:103)
Caused by: java.lang.NoSuchMethodError: net.i2p.util.SystemVersion.getOS()Ljava/lang/String;
    at net.i2p.router.web.ShellService.<init>(ShellService.java:120)
